### ISSUE TITLE
TODO -> Project ideas

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/MEAN-APP#5]
### Infrastructure

- [x] Separate repositories? -> OPTIONAL
- [ ] Build a docker file
- [ ] Get a public domain (.com.ar for example)
- [x] Deploy BE/FE -> (Find where to deploy)
- [ ] Migrate to PostreSQL

### Backend

- [x] Build an entire CRUD
- [x] Build a UML diagram
- [ ] Use JsonWebToken
- [ ] Add a endpoint for login (user/admin)
- [x] Add classes instead of objects

**Comment by jd-apprentice** [comment]
- Separate repositories has been done here -> PR #6

**Comment by jd-apprentice** [comment]
- Deploy has been done in vercel & heroku 
- BE -> [Heroku](https://mean-be.herokuapp.com/api/employees)
- FE -> [Vercel](https://mean-app-fe.vercel.app/)

**Comment by jd-apprentice** [comment]
- [x] Add classes instead of objects -> This is being worked here PR #8

**Comment by jd-apprentice** [comment]
Currently trying this method for using a -> [JWT](https://www.geeksforgeeks.org/jwt-authentication-with-node-js/)

**Comment by jd-apprentice** [comment]
@all-contributors please add @jd-apprentice for code, test, doc and maintenance
